name: package build

on:
  push:
    branches:
    - qt5
    tags:
    - qt5-v*
  pull_request:
    branches:
    - qt5

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        name: [
          linux-x86_64,
        ]
        include:
          - name: linux-x86_64
            os: ubuntu-latest
            arch: x86_64
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - name: build linux
      if: contains(matrix.os, 'ubuntu')
      uses: ./.github/actions/build_linux
    - name: build linux outputs
      if: contains(matrix.os, 'ubuntu')
      run: |
        echo UPLOAD_FILE=cutter-deps-qt5-linux-${{ matrix.arch }}.tar.gz >> $GITHUB_ENV
        echo UPLOAD_ASSET_TYPE=application/gzip >> $GITHUB_ENV
    - uses: actions/upload-artifact@v4
      if: startsWith(github.event.ref, 'refs/tags') == false
      with:
        name: ${{ env.UPLOAD_FILE }}
        path: ${{ env.UPLOAD_FILE }}
        if-no-files-found: warn
    - name: Get release
      if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
      id: get_release
      uses: karliss/get-release@bee343636450eb2e9b85d9f1592d8d73c408dc74
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload release assets
      if: steps.get_release.outputs.upload_url != null
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ${{ env.UPLOAD_FILE }}
          asset_name: ${{ env.UPLOAD_FILE }}
          asset_content_type: ${{ env.UPLOAD_ASSET_TYPE }}
