name: Windows build

on:
  push:
    branches:
    - master
    - qt14 # TODO: remove when branch is done
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: [ windows-latest]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: build
      shell: powershell
      run: ./build_windows.ps1